#run test generator on the simulator
./cache_sc_tester_p ./config_files/config-aes-sim.txt aes-sim.log
cp data basic_aes_sim_results
./cache_sc_tester_p ./config_files/config-gdklibname-sim.txt gdklibname-sim.log
cp data gdklibname_sim_results
./cache_sc_tester_p ./config_files/config-gdklibuni-sim.txt gdklibuni-sim.log
cp data gdklibuni_sim_results
./cache_sc_tester_p ./config_files/config-openaes-sim.txt openaes-sim.log
cp data openssl_aes_sim_results
./cache_sc_tester_p ./config_files/config-opendes-sim.txt opendes-sim.log
cp data openssl_des_sim_results
./cache_sc_tester_p ./config_files/config-openrc4-sim.txt openrc4-sim.log
cp data openssl_rc4_sim_results

#run test generator on the real hardware
./cache_sc_tester_s ./config_files/config-aes-real.txt aes-real.log
cp data basic_aes_real_results
./cache_sc_tester_s ./config_files/config-gdklibname-real.txt gdklibname-real.log
cp data gdklibname_real_results
./cache_sc_tester_s ./config_files/config-gdklibuni-real.txt gdklibuni-real.log
cp data gdklibuni_real_results
./cache_sc_tester_s ./config_files/config-openaes-real.txt openaes-real.log
cp data openssl_aes_real_results
./cache_sc_tester_s ./config_files/config-opendes-real.txt opendes-real.log
cp data openssl_des_real_results
./cache_sc_tester_s ./config_files/config-openrc4-real.txt openrc4-real.log
cp data openssl_rc4_real_results

#go to csv-exec folder. csv-exec is a tool which reads inputs from a csv file and executes a specified target with those inputs in a parallel or a serial fashion
cd ./wrappers/csv-exec
#extract inputs pre-generated by AFL and Radamsa
tar -xf afl.tar.gz
tar -xf radamsa.tar.gz
#run the tests on simuator
execute-simulator.sh
#run the tests on real hardware
execute-local.sh

#go back to root folder
cp ../..

#copy all results to graph folder to prepare plots
cp -f ./wrapper/csv-exec/sim_basic_aes_afl.txt ./plots
cp -f ./wrapper/csv-exec/sim_gdklib_name_afl.txt ./plots
cp -f ./wrapper/csv-exec/sim_gdklib_uni_afl.txt ./plots
cp -f ./wrapper/csv-exec/sim_openssl_aes_afl.txt ./plots
cp -f ./wrapper/csv-exec/sim_openssl_des_afl.txt ./plots
cp -f ./wrapper/csv-exec/sim_openssl_rc4_afl.txt ./plots

cp -f ./wrapper/csv-exec/sim_basic_aes_radamsa.txt ./plots
cp -f ./wrapper/csv-exec/sim_gdklib_name_radamsa.txt ./plots
cp -f ./wrapper/csv-exec/sim_gdklib_uni_radamsa.txt ./plots
cp -f ./wrapper/csv-exec/sim_openssl_aes_radamsa.txt ./plots
cp -f ./wrapper/csv-exec/sim_openssl_des_radamsa.txt ./plots
cp -f ./wrapper/csv-exec/sim_openssl_rc4_radamsa.txt ./plots

cp -f ./wrapper/csv-exec/local_basic_aes_afl.txt ./plots
cp -f ./wrapper/csv-exec/local_gdklib_name_afl.txt ./plots
cp -f ./wrapper/csv-exec/local_gdklib_uni_afl.txt ./plots
cp -f ./wrapper/csv-exec/local_openssl_aes_afl.txt ./plots
cp -f ./wrapper/csv-exec/local_openssl_des_afl.txt ./plots
cp -f ./wrapper/csv-exec/local_openssl_rc4_afl.txt ./plots

cp -f ./wrapper/csv-exec/local_basic_aes_radamsa.txt ./plots
cp -f ./wrapper/csv-exec/local_gdklib_name_radamsa.txt ./plots
cp -f ./wrapper/csv-exec/local_gdklib_uni_radamsa.txt ./plots
cp -f ./wrapper/csv-exec/local_openssl_aes_radamsa.txt ./plots
cp -f ./wrapper/csv-exec/local_openssl_des_radamsa.txt ./plots
cp -f ./wrapper/csv-exec/local_openssl_rc4_radamsa.txt ./plots

#prepare all plots
cd plots
./create_all.sh