/* This file is automatically generated.
   It defines a symbol `__stub_FUNCTION' for each function
   in the C library which is a stub, meaning it will fail
   every time called, usually setting errno to ENOSYS.  */
#define __stub___wait4
#define __stub_chflags
#define __stub_fchdir
#define __stub_fchflags
#define __stub_fexecve
#define __stub_sigpending
